/** Frases del día para empezar la gestión (una por día, en orden). Editables. */
export const FRASES: readonly string[] = [
  "Cada llamada de hoy es una familia que puede estar más protegida mañana.",
  "No vendes un seguro: ayudas a alguien a dormir tranquilo.",
  "La constancia gana más cierres que el talento. Hoy, un contacto más.",
  "Escucha primero: la mejor propuesta nace de una buena pregunta.",
  "Un 'no' de hoy es información, no un final. Sigue con actitud.",
  "Tu energía al saludar es la primera impresión de tu asesoría.",
  "Pequeñas gestiones diarias construyen grandes metas a fin de mes.",
  "Quien se siente escuchado, confía. Quien confía, decide.",
  "Hoy es un buen día para pedir un referido.",
  "Prepárate como si cada reunión fuera la más importante del mes.",
  "La disciplina de hoy es la comisión de mañana.",
  "Ayuda primero; el cierre llega como consecuencia.",
  "Cada seguimiento a tiempo es una puerta que se mantiene abierta.",
  "Habla de lo que le importa a tu cliente, no de lo que quieres vender.",
  "Una sonrisa también se escucha por teléfono.",
  "Tu meta del mes se construye contacto por contacto.",
  "La honestidad es tu mejor argumento de venta.",
  "Termina lo que empiezas: cada contacto merece un cierre, sea sí o sea no.",
  "Haz hoy la llamada que estás posponiendo.",
  "Proteger la salud de una familia es un trabajo que vale la pena hacer bien.",
  "Sé el asesor que tú quisieras tener.",
  "El mejor momento para dar seguimiento era ayer; el segundo mejor es hoy.",
  "Organiza tu día y tu día trabajará para ti.",
  "Cada objeción es una pregunta que aún no has respondido.",
  "Tu actitud define el tono de cada conversación.",
  "Celebra los avances pequeños: también te acercan a la meta.",
  "Un cliente bien atendido es tu mejor fuente de referidos.",
  "Conoce a fondo antes de proponer: así se gana la confianza.",
  "Enfócate en lo que puedes controlar: tu gestión de hoy.",
  "Hoy siembras relaciones; los cierres son la cosecha.",
  "Empieza con energía, termina con orgullo.",
];
